services:
  app:
    build:
      dockerfile: infrastructure/docker/Dockerfile
      context: . 
      target: dev
    env_file:
      - .env
    volumes:
      - .:/code
      - pkg:/go/pkg/mod
    working_dir: /code
    depends_on:
      - rabbitmq
      - mongodb

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    attach: false

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    command: --bind_ip localhost,mongodb,127.0.0.1
    volumes:
      - mongo:/data/db
    attach: false

volumes:
  pkg:
  mongo:
