apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-fileserver.fullname" . }}-config
  labels:
    {{- include "nginx-fileserver.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Values.nginx.config | nindent 4 }}