# Configuration for the gateway
gateway:
  # -- Specifies whether the gateway should be enabled
  enabled: true

  # Basic auth configuration
  basicAuth:
    # -- Enables basic authentication for the gateway
    enabled: true
    existingSecret: tempo-gateway-basic-auth

  # Ingress configuration to allow external Grafana access
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/enable-cors: "true"  # Enable CORS
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"  # Allow requests from Grafana's domain
      nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"  # Allow the necessary HTTP methods
      nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"  # Allow necessary headers
    ingressClassName: nginx
    tls:
      - hosts:
          - tempo.obs.opendatahub.com
        secretName: tls-tempo
    hosts:
      - host: tempo.obs.opendatahub.com
        paths:
          - path: /
            pathType: Prefix