services:
  bdp:
    image: "ghcr.io/noi-techpark/opendatahub-timeseries-writer/opendatahub-timeseries-writer-app:latest"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_DB: bdp
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA: intimev2
      POSTGRES_SERVER: db
      POSTGRES_USERNAME: bdp
      POSTGRES_PASSWORD: password

      HIBERNATE_LOG_LEVEL: warn
      HIBERNATE_MAX_POOL_SIZE: 15
      HIBERNATE_SQL_LOG: "false"

      KEYCLOAK_CLIENT_ID: odh-mobility-writer-development
      KEYCLOAK_CLIENT_SECRET: a0c41578-7f31-4b52-8efe-fab8aece34da
      KEYCLOAK_REALM: noi
      KEYCLOAK_SSL_REQUIRED: none
      KEYCLOAK_URL: https://auth.opendatahub.testingmachine.eu/auth

      LOG_APPLICATION_NAME: writer
      LOG_APPLICATION_VERSION: 0.0.1-localdev
      ROOT_LOG_LEVEL: info
      LOG_LEVEL: debug
      LOG_STYLE: json

      SECURITY_ALLOWED_ORIGINS: "*"
      SERVER_PORT: 8991
    ports:
      - "8081:8991"

  # In case you had postgres running and changed some parameters here, docker-compose
  # might reuse the existing volume and not update your password, DB or role.
  # So stop the containers and execute 'docker-compose rm -fv db' to get rid
  # of cached databases
  db:
    image: postgis/postgis:12-3.2-alpine
    environment:
      POSTGRES_DB: bdp
      POSTGRES_USER: bdp
      POSTGRES_PASSWORD: password
    ports:
      - "5555:5432"
    tty: true
        
  ninja:
    image: "ghcr.io/noi-techpark/opendatahub-timeseries-api/opendatahub-timeseries-api-app:latest"
    restart: unless-stopped
    depends_on: 
      - bdp
    environment:
      SERVER_PORT: 8991
      SECURITY_ALLOWED_ORIGINS: "*"

      NINJA_BASE_URL: http://localhost:8991
      NINJA_HOST_URL: http://localhost:8991
      NINJA_QUERY_TIMEOUT_SEC: 30
      NINJA_RESPONSE_MAX_SIZE_MB: 100

      KEYCLOAK_CLIENT_ID: odh-mobility-writer-development
      KEYCLOAK_CLIENT_SECRET: a0c41578-7f31-4b52-8efe-fab8aece34da
      KEYCLOAK_REALM: noi
      KEYCLOAK_SSL_REQUIRED: none
      KEYCLOAK_URL: https://auth.opendatahub.testingmachine.eu/auth

      LOG_APPLICATION_NAME: ninja
      LOG_APPLICATION_VERSION: 0.0.0-local-dev

      JDBC_URL: jdbc:postgresql://db:5432/bdp?currentSchema=intimev2,public
      DB_USERNAME: bdp
      DB_PASSWORD: password
    ports:
      - "8082:8991"

  analytics:
    build: 
      context: .
      dockerfile_inline: |
        FROM ghcr.io/noi-techpark/opendatahub-timeseries-analytics/opendatahub-timeseries-analytics:cf04facd63c4a55a00f1d38ddc5cae248f397533
        RUN cat <<EOF > /usr/share/nginx/html/dotenv.js
        window.env = {
          SERVER_PORT: "8999",
          ENDPOINT_URL: "http://localhost:8999",
          ODH_MOBILITY_API_URI: "http://localhost:8082",
          LOG_APPLICATION_NAME: "opendatahub-analytics",
          THUNDERFOREST_MAP_API_KEY: "",
          KEYCLOAK_AUTHORIZATION_URI: "https://auth.opendatahub.testingmachine.eu/auth",
          KEYCLOAK_REALM: "noi",
          KEYCLOAK_CLIENT_ID: "odh-mobility-analytics",
          KEYCLOAK_REDIRECT_URI: "http://localhost:8999/",
          KEYCLOAK_SILENT_CHECK_SSO_REDIRECT_URI: "http://localhost:8999/callback.html",
          GOOGLE_ANALYTICS_ID: "not-used"
        }
        EOF
    depends_on: 
      - ninja
    ports:
      - "8999:80"