# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0
# 
include:
  - docker-compose.yml

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5671:5671"
      - "5672:5672"
      - "4369:4369"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: nc -z localhost:5672
    attach: false

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    command: --replSet rs0 --bind_ip localhost,mongodb,127.0.0.1 --port 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    attach: false
      
  # Initializes replicaset once after it has been started
  mongodb-init:
    image: mongo
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    entrypoint: |
      mongosh "mongodb://mongodb" --eval "
        try{
          rs.initiate({
            _id : 'rs0',
            members: [
              { _id : 0, host : 'mongodb:27017' },
            ]
          })
        } catch(error) {
          // Already initialized. that's fine
          if (error.code != 23) {
            throw(error)
          }
        }"
          
  # Writer service listens on ingress queue and writes raw data to mongodb
  writer:
    image: ghcr.io/noi-techpark/infrastructure-v2/raw-writer:latest
    pull_policy: always
    environment:
      APP_MQ_URI: amqp://guest:guest@rabbitmq:5672
      APP_MQ_EXCHANGE: ingress
      APP_MQ_QUEUE: ingress
      APP_MQ_READY_EXCHANGE: ready
      APP_MONGO_URI: mongodb://mongodb/?replicaSet=rs0&directConnection=true
      APP_LOGLEVEL: INFO
    depends_on:
      mongodb-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy

  # Router service listens on ready exchange (where writer writes) and distributes messages according to routing key
  router:
    image: ghcr.io/noi-techpark/infrastructure-v2/router:latest
    pull_policy: always
    environment:
      APP_MQ_URI: amqp://guest:guest@rabbitmq:5672
      APP_MQ_READY_EXCHANGE: ready
      APP_MQ_READY_QUEUE: ready
      APP_MQ_ROUTED_EXCHANGE: routed
      APP_MQ_ROUTED_QUEUE: routed
    depends_on:
      mongodb-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy  
        
  # Resource lookup service
  bridge:
    image: ghcr.io/noi-techpark/infrastructure-v2/raw-data-bridge:latest
    pull_policy: always
    environment:
      APP_MONGO_URI: mongodb://mongodb/?replicaSet=rs0&directConnection=true
    depends_on:
      mongodb-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    ports:
      - 2000:2000

networks:
  default:
    name: ingestion
    attachable: true
