apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: digital@noi.bz.it
    privateKeySecretRef:
      name: letsencrypt-dns-staging
    solvers:
      - dns01:
          route53:
            region: eu-west-1
