# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

# Default values for analytics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/it.bz.opendatahub.analytics/it.bz.opendatahub.analytics
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: d21bcb682eb934e4d108548ae2d3ffa1de56d6ef 

nameOverride: "analytics"
fullnameOverride: "analytics"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"

  className: nginx
  tls:
    - hosts:
      - analytics.dev.testingmachine.eu
      secretName: tls-analytics
  hosts:
    - host: analytics.dev.testingmachine.eu
      paths: 
        - path: "/"
          pathType: Prefix