# Default values for analytics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/it.bz.opendatahub.analytics/it.bz.opendatahub.analytics
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "6b984ebe28d00019a59e4e805254b888183db994"

nameOverride: "analytics"
fullnameOverride: "analytics"

service:
  type: NodePort
  port: 80

ingress:
  enabled: true

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
 
  className: alb

  paths: 
    - path: "/*"
      pathType: ImplementationSpecific
      port: 80