# Default values for raw-writer-2.
replicaCount: 2

image:
  repository: ghcr.io/noi-techpark/infrastructure-v2/raw-writer-2
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  - name: MONGO_URI
    value: mongodb://user:password@mongodb
  - name: DB_PREFIX
    value: rawdata
  - name: S3_BUCKET
    value: raw-data
  - name: S3_ENDPOINT
    value: ""
  - name: S3_REGION
    value: eu-west-1
  - name: MQ_URI
    value: amqp://user:password@rabbitmq
  - name: MQ_CLIENT_NAME
    value: raw-writer-2
  - name: MQ_READY_EXCHANGE
    value: ready
  - name: MQ_READY_QUEUE
    value: ready
  - name: MQ_READY_DL_QUEUE
    value: ready-dl

podAnnotations: {}
podLabels: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
