apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anshar.fullname" . }}-config
  labels:
    {{- include "anshar.labels" . | nindent 4 }}
type: Opaque
stringData:
  application.properties: |
    {{- .Values.config.applicationProperties | nindent 4 }}
  subscriptions.yml: |
    {{- .Values.config.subscriptionsYml | nindent 4 }}
