# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: v2
name: raw-data-bridge
description: Resource Lookup service
type: application
version: 1.0.0
appVersion: "1.0.0"
