image:
  tag: "2026-05-29T13-12"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: siri.api.dev.opendatahub.testingmachine.eu
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: anshar-tls
      hosts:
        - siri.api.dev.opendatahub.testingmachine.eu

config:
  applicationProperties: |
    spring.main.sources=no.rutebanken.anshar

    spring.profiles.active=in-memory-blobstore

    server.shutdown=graceful

    anshar.environment=local

    spring.main.web-application-type=none
    spring.main.allow-circular-references=true

    anshar.subscriptions.config.path=./subscriptions.yml

    anshar.incoming.logdirectory=target/incoming
    anshar.incoming.port = 8012

    management.endpoints.web.exposure.include=info, health, prometheus, env, metrics, loggers
    management.endpoints.prometheus.enabled=true
    management.metrics.endpoint.export.prometheus.enabled=true
    management.health.pubsub.enabled=false

    camel.metrics.enable-route-event-notifier=false
    camel.metrics.enable-route-policy=false
    camel.metrics.enable-exchange-event-notifier=false

    anshar.validation.total.max.size.mb=4
    anshar.validation.total.max.count=20
    anshar.validation.data.persist.hours=6

    anshar.validation.profile.name=norway
    anshar.validation.profile.enabled=true

    anshar.siri.default.producerRef=ENT

    anshar.incoming.concurrentConsumers=5

    anshar.default.max.elements.per.delivery=1000

    anshar.inbound.url = http://localhost
    anshar.healthcheck.interval.seconds = 30

    anshar.healthcheck.hubot.url=http://hubot/hubot/say
    anshar.healthcheck.hubot.payload.source=anshar
    anshar.healthcheck.hubot.payload.icon.fail=:heavy_exclamation_mark:
    anshar.healthcheck.hubot.payload.icon.success=:heavy_check_mark:
    anshar.healthcheck.hubot.payload.message.fail=Not receiving data: {0}
    anshar.healthcheck.hubot.payload.message.success=Subscriptions back to normal
    anshar.healthcheck.hubot.payload.template=\"source\":\"{0}\", \"icon\":\"{1}\", \"message\":\"{2}\"
    anshar.healthcheck.hubot.allowed.inactivity.minutes=15
    anshar.healthcheck.hubot.start.time= 06:00
    anshar.healthcheck.hubot.end.time= 23:00

    anshar.admin.health.allowed.inactivity.seconds = 300

    anshar.mapping.update.frequency.min=60

    anshar.route.singleton.policy.ignore = false
    anshar.route.singleton.policy.lockValue = localhost
    anshar.route.singleton.policy.automatic.verification=false

    anshar.inbound.pattern  = /{context}/{version}/{type}/{vendor}/{subscriptionId}/{service}/{operation}

    anshar.siri.et.graceperiod.minutes=10
    anshar.siri.sx.graceperiod.minutes=10
    anshar.siri.vm.graceperiod.minutes=10
    anshar.siri.fm.graceperiod.minutes=10

    anshar.tracking.data.buffer.commit.frequency.seconds=15

    anshar.outbound.polling.tracking.period.minutes=10
    anshar.outbound.adhoc.tracking.period.minutes=2

    anshar.outbound.heartbeatinterval.minimum=30000
    anshar.outbound.heartbeatinterval.maximum=60000

    anshar.outbound.error.initialtermination=InitialTerminationTime has already passed.
    anshar.outbound.error.consumeraddress=ConsumerAddress must be set.

    anshar.outbound.error.graceperiod.factor=3
    anshar.outbound.error.graceperiod.minimum=PT1M
    anshar.outbound.error.redelivery.delay.millis=1000
    anshar.outbound.timeout.socket=15000
    anshar.outbound.timeout.connect=5000

    anshar.outbound.pubsub.topic.enabled=false
    anshar.outbound.pubsub.et.topic.enabled=false
    anshar.outbound.pubsub.vm.topic.enabled=false
    anshar.outbound.pubsub.sx.topic.enabled=false
    anshar.outbound.pubsub.fm.topic.enabled=true

    anshar.message.queue.camel.route.prefix=direct://

    spring.cloud.gcp.project-id=test
    spring.cloud.gcp.pubsub.project-id=test

    anshar.export.snapshot.cron.expression=
    anshar.export.snapshot.tmpFolder=/deployments/export/
    blobstore.gcs.project.id=carbon-1287
    blobstore.gcs.container.name=anshar-test

    anshar.bigdata.siri.et.export.camel.url=

    anshar.tracking.header.required.post=false
    anshar.tracking.header.required.get=false
    anshar.tracking.header.name=ET-Client-Name

    spring.security.user.name=usr
    spring.security.user.password=pwd

    anshar.kafka.enabled=false
    anshar.kafka.clientId=anshar
    anshar.kafka.brokers=
    anshar.kafka.security.protocol=
    anshar.kafka.security.sasl.mechanism=
    anshar.kafka.sasl.username=
    anshar.kafka.sasl.password=

    anshar.kafka.siri.enrich.et.enabled=false

    anshar.login.username=user
    anshar.login.password=pass

    anshar.reduced.logging.override.names=no.rutebanken.anshar.routes.siri.handlers.SiriHandler

    anshar.startup.wait.for.netex.initialization=false
    anshar.startup.load.mapping.data=false

    anshar.mapping.adapters.disabled=true

    anshar.pubsub.avro.et.enabled=false
    anshar.pubsub.avro.vm.enabled=false
    anshar.pubsub.avro.sx.enabled=false
    anshar.pubsub.avro.fm.enabled=false

  subscriptionsYml: |
    anshar:
      subscriptions:
        -
          internalId: 100
          vendor: SAD
          name: SAD - trains
          datasetId: SADtrains
          serviceType: REST
          subscriptionType: VEHICLE_MONITORING
          subscriptionMode: REQUEST_RESPONSE
          heartbeatIntervalSeconds: 60
          updateIntervalSeconds: 1
          operatorNamespace: http://www.siri.org.uk/siri
          addressFieldName:
          soapenvNamespace:
          incrementalUpdates:
          urlMap:
            GET_VEHICLE_MONITORING: http://files-nginx-external.core.svc.cluster.local/siri-lite/vehicle-monitoring/trains/sad.xml
          version: 2.0
          contentType: text/xml;charset=UTF-8
          subscriptionId: anshar-example-${random.uuid}
          requestorRef: anshar-example-${random.uuid}
          durationOfSubscriptionHours: 1680
          mappingAdapterId: entur
          filterPresets:
          idMappingPrefixes:
          codespaceWhiteList: TST
          active: true
          validation: false
