controller:
  service:
    create: true
    httpPort.enable: false
    annotations:
      # Exchange ID with output of terraform dns eks-ingress-name
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-name: eks-nginx-public
      service.beta.kubernetes.io/aws-load-balancer-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-eip-allocations: <aws eipalloc ID>
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-subnets: internal-vpc-public-eu-west-1b