image:
  repository: kind/infrastructure-v2/router
  pullPolicy: IfNotPresent
  tag: "v1.0"

env:
  - name: SERVICE_NAME
    value: router
  - name: APP_MQ_URI
    value: amqp://user:zAPl04iM1L10YAKU@rabbitmq-cluster-headless.default.svc.cluster.local:5672
  - name: APP_MQ_READY_EXCHANGE
    value: ready
  - name: APP_MQ_READY_QUEUE
    value: ready
  - name: APP_MQ_ROUTED_EXCHANGE
    value: routed
  - name: APP_MQ_ROUTED_QUEUE
    value: routed
  - name: APP_LOGLEVEL
    value: DEBUG
  - name: LOG_LEVEL
    value: DEBUG

  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://tempo.grafana.svc.cluster.local:4317

# resources:
#   limits:
#     cpu: 250m   # 250m is equivalent to 0.25 CPU core
#     memory: 500Mi
#   requests:
#     cpu: 100m   # 100m is equivalent to 0.1 CPU core
#     memory: 100Mi
