# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

image:
  repository: ghcr.io/noi-techpark/odh-infrastructure-v2/notifier
  pullPolicy: Always # Workaround: this is necessary since we are using the `latest` tag.
  tag: latest # Woraround: ideally here we should use the image `sha256` unique hash.
  imagePullSecrets: container-registry-r

env:
  - name: MONGODB_CONNECTION_STRING
    valueFrom:
      secretKeyRef: 
        name: mongodb-svcbind
        key: uri
  - name: MONGODB_CONNECTION_REPLICA_SET
    value: rs0
  - name: RABBITMQ_CLUSTER_URL
    valueFrom:
      secretKeyRef: 
        name: rabbitmq-svcbind
        key: uri