image:
  repository: 463112166163.dkr.ecr.eu-west-1.amazonaws.com/notifier
  tag: latest

env:
  - name: MONGODB_CONNECTION_STRING
    value: mongodb://mongodb-0.mongodb-headless.default.svc.cluster.local:27017
  - name: MONGODB_CONNECTION_REPLICA_SET
    value: rs0
  - name: RABBITMQ_CLUSTER_URL
    value: user:90SK1AeldgRh7TzE@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local:5672
