# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

image:
  repository: 463112166163.dkr.ecr.eu-west-1.amazonaws.com/notifier
  pullPolicy: Always # Workaround: this is necessary since we are using the `latest` tag.
  tag: latest # Woraround: ideally here we should use the image `sha256` unique hash.

env:
  - name: MONGODB_CONNECTION_STRING
    value: mongodb://mongodb-0.mongodb-headless.default.svc.cluster.local:27017
  - name: MONGODB_CONNECTION_REPLICA_SET
    value: rs0
  - name: RABBITMQ_CLUSTER_URL
    value: guest:guest@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local:5672
