# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

# https://artifacthub.io/packages/helm/naps/mosquitto
fullnameOverride: mosquitto

mosquitto:
  config: |
    autosave_interval 60
    autosave_on_changes false
    allow_anonymous true

  persistence:
    enabled: true
    path: /mosquitto/data
