# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

@host=http://localhost:2000
###
GET {{host}}/urns/urn:raw:lorawan:data:67a9db400696ac3cf49b07c0
### Object as rawdata
GET {{host}}/urns/urn:raw:a22:environment:6891e54b9237c6dd3479712f
### Huge json as string
GET {{host}}/urns/urn:raw:s3-poller:meteorology-bz-forecast:67a4ce70d3a62887e54455e2
### Has an array as rawdata
GET {{host}}/urns/urn:raw:parking-offstreet-famas:bolzano:683ff7249237c6dd345cbf29
