image:
  repository: ghcr.io/noi-techpark/infrastructure-v2/raw-data-bridge
  pullPolicy: Always
  tag: "v1.0"

env:
  - name: APP_MONGO_URI
    valueFrom:
      secretKeyRef: 
        name: mongodb-collector-svcbind
        key: uri
  - name: APP_LOG_LEVEL
    value: INFO
  - name: SERVICE_NAME
    value: raw-data-bridge
  - name: TELEMETRY_TRACE_GRPC_ENDPOINT
    value: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

# resources:
#   limits:
#     cpu: 250m   # 250m is equivalent to 0.25 CPU core
#     memory: 500Mi
#   requests:
#     cpu: 100m   # 100m is equivalent to 0.1 CPU core
#     memory: 100Mi
