image:
  repository: kind/infrastructure-v2/raw-data-bridge
  pullPolicy: IfNotPresent
  tag: "v1.0"

env:
  - name: SERVICE_NAME
    value: raw-data-bridge
  - name: APP_MONGO_URI
    value: mongodb+srv://mongodb-headless.core.svc.cluster.local/?tls=false&ssl=false
  - name: APP_LOGLEVEL
    value: DEBUG  
  - name: LOG_LEVEL
    value: DEBUG

  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://tempo.grafana.svc.cluster.local:4317

# resources:
#   limits:
#     cpu: 250m   # 250m is equivalent to 0.25 CPU core
#     memory: 500Mi
#   requests:
#     cpu: 100m   # 100m is equivalent to 0.1 CPU core
#     memory: 100Mi
