# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

# https://artifacthub.io/packages/helm/camel-k/camel-k
platform:
  build:
    registry:
      # !!! Amazon ECR is not supported yet by Kamel, use Docker Hub instead.
      # !!! See https://github.com/apache/camel-k/issues/4107.
      # address: 463112166163.dkr.ecr.eu-west-1.amazonaws.com
      # secret: docker-secrets
      # organization: kamel
      address: 828408288281.dkr.ecr.eu-west-1.amazonaws.com
      secret: ecr-secrets
      organization: camel

# Before deploying Camel-K remember to create the required docker secrets:
#
# kubectl create secret docker-registry docker-secrets \                 
#   --docker-username="..." \                                             
#   --docker-password="..."
#
# or you can add this step to the GitHub Actions pipeline:
#
# kubectl create secret docker-registry docker-secrets \                 
#   --docker-username="${{ secrets.DOCKER_REGISTRY_USERNAME }}" \                                             
#   --docker-password="${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
