# https://artifacthub.io/packages/helm/camel-k/camel-k
platform:
  build:
    registry:
      # !!! Amazon ECR is not supported yet by Kamel, use Docker Hub instead.
      # !!! See https://github.com/apache/camel-k/issues/4107.
      # address: 463112166163.dkr.ecr.eu-west-1.amazonaws.com
      # secret: docker-secrets
      # organization: kamel
      address: docker.io
      secret: docker-secrets
      organization: roggia
