# Default values for ninja-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/it.bz.opendatahub.api.mobility-ninja/it.bz.opendatahub.api.mobility-ninja-app 
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "unstable"

nameOverride: "ninja-api"
fullnameOverride: "ninja-api"
  
health:
  delay: 40
    
service:
  type: NodePort
  port: 8081

ingress:
  enabled: true

  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"

  className: nginx
  tls:
    - hosts:
      - mobility.api.dev.testingmachine.eu
      secretName: tls-ninja-api
  hosts:
    - host: mobility.api.dev.testingmachine.eu
      paths: 
        - path: "/"
          pathType: Prefix

env: 
  SERVER_PORT: 8081
  NINJA_BASE_URL: https://mobility.api.dev.testingmachine.eu
  NINJA_HOST_URL: https://mobility.api.dev.testingmachine.eu
  NINJA_QUERY_TIMEOUT_SEC: 30
  NINJA_RESPONSE_MAX_SIZE_MB: 100

  # Quota: Requests per second for:
  # - a guest user (anonymous request)
  # - a guest user that provides a referer header
  # - a logged-in user without a contract : > BASIC
  # - a logged-in user with a ADVANCED contract
  # - a logged-in user with a PREMIUM contract
  # - admins have no restrictions at all
  NINJA_QUOTA_GUEST: 5
  NINJA_QUOTA_REFERER: 10
  NINJA_QUOTA_BASIC: 20
  NINJA_QUOTA_ADVANCED: 50
  NINJA_QUOTA_PREMIUM: 100

  # Quota: Historical data request range limit in days. See request rate quota above for user types
  #NINJA_QUOTA_HISTORY_GUEST: 30
  #NINJA_QUOTA_HISTORY_REFERER: 60
  #NINJA_QUOTA_HISTORY_BASIC: 365
  #NINJA_QUOTA_HISTORY_ADVANCED: 1095
  #NINJA_QUOTA_HISTORY_PREMIUM: 9999999

  ### Logging
  # Identification of the log entries, if used together with other applications
  # Make sure that the application name and version corresponds to your pom.xml
  # "artifactId" and "version".
  LOG_APPLICATION_NAME: ninja
  LOG_APPLICATION_VERSION: 0.0.0-LOCAL-DEV
  LOG_LEVEL: DEBUG
  LOG_ROOTLEVEL: INFO
  # text or json
  LOG_STYLE: text

  SECURITY_ALLOWED_ORIGINS: "*"
  KEYCLOAK_URL: https://auth.opendatahub.testingmachine.eu/auth/
  KEYCLOAK_SSL_REQUIRED: none
  KEYCLOAK_REALM: noi
  KEYCLOAK_CLIENT_ID: odh-mobility-v2
  KEYCLOAK_CLIENT_SECRET: 

  # In case you don't have a servicebind secret, you can use these env variables
  # JDBC_URL: "jdbc:postgresql://odh-postgres.czracduepxal.eu-west-1.rds.amazonaws.com:5432/bdp?currentSchema=intimev2,public"
  # DB_USERNAME: bdp_readonly
  # DB_PASSWORD: <pass by commandline>

  #JAVA_OPTIONS: -Xms2g -Xmx6g
  #
database:
  servicebindName: "postgres-read-svcbind"