# Default values for bdp-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/bdp-core/bdp-core-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "renamed"

nameOverride: "bdp-core"
fullnameOverride: "bdp-core"
  
service:
  port: 8080
  type: ClusterIP
  
health:
  delay: 30
    
env: 
  SERVER_PORT: 8080
  ### Security
  SECURITY_ALLOWED_ORIGINS: "*"
  KEYCLOAK_URL: https://auth.opendatahub.testingmachine.eu/auth
  KEYCLOAK_SSL_REQUIRED: none
  KEYCLOAK_REALM: noi
  KEYCLOAK_CLIENT_ID: odh-mobility-writer-development
  LOG_LEVEL: INFO
  LOG_STYLE: json
  LOG_APPLICATION_NAME: writer
  HIBERNATE_SQL_LOG: false
  HIBERNATE_LOG_LEVEL: WARN

  # If you don't use servicebind, set these as env
  # POSTGRES_SERVER: postgres.hostname.com
  # POSTGRES_PORT: 5432
  # POSTGRES_DB: bdp
  # POSTGRES_USERNAME: bdp
  # POSTGRES_PASSWORD: <pass by commandline>
  #
  POSTGRES_SCHEMA: intimev2
  
database:
  servicebindName: "postgres-readwrite-svcbind"