name: REUSE Lint

on:
  push:
  pull_request:

jobs:
  reuse-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install reuse tool
        run: pip install reuse

      - name: Run reuse lint
        run: reuse lint --fail-on-error
