mongodb:
    rootPassword: ENC[AES256_GCM,data:ufBBFcSroXndto78h6BdvfETBvoU83pN,iv:+S2z9wefWzM2HXxLd6rLcr9tEQ28iDzq4yxT+lJ7PTs=,tag:Qv6Q7sjxB3AUPfKEOJVW4Q==,type:str]
    replicaSetKey: ENC[AES256_GCM,data:xFCoTuauHjQbVjAFCs4UlYjbqCs+/Vy/25ecKJubVyJR5xXwfONnzTYkqn/pdZANFUyTktYJuerh25MNlUIU3Q==,iv:2iEJIA53VultSrHKHKsrthSh30zNzc3FwvZgvk9lwyc=,tag:vYi9BXNlxPTqoONaxvUHhw==,type:str]
    users:
        writer: ENC[AES256_GCM,data:QO8vfnTKoIVGO3IyuwTFqZwkfSZ+oxpO,iv:K02KSYiZeYykM1xS6srWf9BZtuUC8pPW3ELkziZmvO4=,tag:86j/bSlH06FZnNGW+bQXZw==,type:str]
        notifier: ENC[AES256_GCM,data:sgY/91/0EPl5Q+CPuuUMvErxREr21GzQ,iv:VKdTaSOKxME4LreIBUYsp5IESCTt9QTZ34/W/SV2dKk=,tag:CfFuvyJcx3jq6MsUGvUdCw==,type:str]
        collector: ENC[AES256_GCM,data:FucXRq8QZKPD1NCl2lSokN78hPwUXlps,iv:M2ObHqvBkSWjkCgWOPYljqPhk+HjgpE4n3xI3yyY/B0=,tag:V2Z/IokIuwKC+/F/NdZjlA==,type:str]
        prometheus: ENC[AES256_GCM,data:34uHmtvAecUStVSzaLhZ27piH8f+ciw1,iv:uiVh3EHbPXtuJSHRIFMILV2GuD0AfFBvPRmBlbaBJEY=,tag:OmQBJtuwKyOmXA1oYNegBA==,type:str]
rabbitmq:
    password: ENC[AES256_GCM,data:1JOt/nKJ2i/gbGpr6kJG8YQK+PLsOtpw,iv:TaziDI3aR/6TliPGnXA4TcWU0+roKrX6IH0wYU2miUc=,tag:pxZDQhhfq/b+9zWoYsOn3g==,type:str]
    erlangCookie: ENC[AES256_GCM,data:pyoB6tZhs2CFLFxI/opSyCl+tQE0tANE5PWT5Hk590k=,iv:fQDYolb5YdP469B+rxehSVsE7axg9N7XmtfgnuKBExs=,tag:/Am7ypzffLqYSIA/s5NNdA==,type:str]
basicAuth:
    tempo:
        password: ENC[AES256_GCM,data:xC8Hh1msTLyrE0OYH73M5ZsXwxmZWl2P,iv:51fvICeiqXGCZshUhS8R8uTHy3ZXuePz+eIcE2M/pqk=,tag:8+BP4+7zc64Eyqmw962QLw==,type:str]
        htpasswd: ENC[AES256_GCM,data:b9aRdI9wMtCM7T4fyCc1OTkVtTKjy3fEve4FFU15TsnFgGX3lVy4Cv4hsC0+gA==,iv:kZ0vuWm558JTsou8aWb5uVltojDCVDSazmxzX5r2ywU=,tag:rN3ZelcyPnFgwcKDBSaIsQ==,type:str]
    prometheus:
        password: ENC[AES256_GCM,data:iIS/5WM6EONswpHkAwTfKT30v6qcwYgs,iv:hcNplDINj4e17Wn2mPSp34Rp2NYZOiatDF8Sl5b5sm8=,tag:pZBiqUa7Q+YoAkXrM5Z/pg==,type:str]
        htpasswd: ENC[AES256_GCM,data:gnZo9y8xcohFfSfvlp/b/igCjOAKUrroHmlmy6GmeroRtFJZSyk3fK5970cNgw==,iv:b432DsyaaSD9WfABKeQ3MBOHL3xZE4qs89VLJd5h/90=,tag:3N+kO7CGoiulkibe/1/DQQ==,type:str]
    rawDataBridge:
        password: ENC[AES256_GCM,data:dbjH63M17NIXgl9uaPFDaEkN6Rzfy527,iv:kHV823oUqVCdVhQ9DFVelLVg1Z70uOASjjWR1Zcu6t8=,tag:8guPThy1WHUFoNPQ6Pga1g==,type:str]
        htpasswd: ENC[AES256_GCM,data:F1V/4EWpdq5K6vKv3jWIykEJLXa2WcntiXUi6ATThDzVoo8ZhzPpo0JsRPewfg==,iv:/4uekKb8aE4ewIaLvkcvox3wYLKphY1oBlvOZGwu3Vs=,tag:ovu7HGz4ghbPKJary+Q6PA==,type:str]
registry:
    readToken: ""
    readWriteToken: ""
postgres:
    host: ""
    port: ""
    readwritePassword: ""
    readonlyPassword: ""
rawS3:
    bucketName: ""
    accessKeyId: ""
    secretAccessKey: ""
velero:
    accessKey: ""
    secretKey: ""
scalewayDns:
    accessKey: ""
    secretKey: ""
oauthCollector:
    clientSecret: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXblo2YnFRU1RnYmtHSFBm
            NXh3NktIRjN1a3JsK1ZPTXpraTFtMkpZbWxzCkw2NlNKa3Y4ZG9QSGpmSW1SRXZn
            dnN4NHNLaW04OEFVaDVrK2lSWVNST2MKLS0tIC9xa3JCZmpJMk1qempSRmxONFVy
            aUcwMFl6TDZweWRZeTFnMWQ2K3BTM1EKGd/VJKoX4EWa3vFYvZBMKQ4HD07SBw77
            58crC5xEvXsrlLRNKoM3YR09Brr997AIVAlAg157T8W2L3jfSiYVcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cnpfwnkz3pjyyalxg38a63el9l06dw4g8a3w3jyraykpfzsy2clqevkrh3
    lastmodified: "2026-10-01T07:31:43Z"
    mac: ENC[AES256_GCM,data:MDZB69OBQjAvyvT5lWjenw8Mn8fAN64CrpjtZ8CCRGgdu9NEzbm4iwZpF3X6ECwYA03ETU3rbDgRZrM/Bv/TUWbLc07l43P3D7K14uqATYb1rMwyo0vafN+bZMSlFZJHnoITVjLGXzdB6vIDRTUEWscxi80ndxJb3Z1PIForJwk=,iv:q1XhW8d9aZtYRDCfRBzJDI+9n6EMQMCSCHjQ8GzGiqA=,tag:EQCXGq1Pyw6vnzqP5NMjKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
