mongodb:
    rootPassword: ENC[AES256_GCM,data:HOR7J1tZWvnxNTkVCyiGm2IbQNzDoZ4n,iv:4iJP1VeYZqbbVsqujPW0b36b+6srN9BV3V4jpftXFoo=,tag:GsGu2sQ9TC1HivytES2H3w==,type:str]
    replicaSetKey: ENC[AES256_GCM,data:6Jj1pzwRpsMeRXikzSr9BArskYakAMWZ8v3rAo+rSRXqWVVjWx63U01n1di0wOsFGgK+gY6h6oNeNSbN5c4B6w==,iv:Jd09KvL+U4/bH8p6pFc9RUdQLz7lm56Z39x8MQKjJqw=,tag:4b5yW2A79Vxy2YoYoJwSLw==,type:str]
    users:
        writer: ENC[AES256_GCM,data:lmTcbkk35CYFl4NI9LWNVyTef5CI0mZO,iv:xvZfnEHrfBwqJgbcaaQ/l2IEpNVj+9YT8NWfV2XoqUk=,tag:RLzU++txznYsKFsKSLO5pQ==,type:str]
        notifier: ENC[AES256_GCM,data:QinaozErFWG/W7UWNLovsPy+9JD6mMsg,iv:oyijn4oHhFyqZ2Gdi+xsy6TvIL6Z2fV89ZwX4DQG7vY=,tag:kPNbDWTO349vxf1M2ivp2A==,type:str]
        collector: ENC[AES256_GCM,data:V4LkJz3/V84PeFjGj8O60nJw+FxtAcRS,iv:3lNbGWBRUsecX7ZNuin5u885dIf7vzpRwqZbTNAFeF4=,tag:soyew+V2v3cJmLAmIOQ+6g==,type:str]
        prometheus: ENC[AES256_GCM,data:0J6jOe9dyEBqPmwaXPQbgl0I+EkOtNuM,iv:dN8SL32aBiF92ZstXAg12EdMKddr24J8guwh4YG0jTo=,tag:iTPrQ0hQp0Nar25U7iZ33Q==,type:str]
rabbitmq:
    password: ENC[AES256_GCM,data:xjYos2/OC+T1lW/Yl7ud/HGDsoEigNCw,iv:p+GboemhDlCu4Acq2pxC5yS6AJ+7Z8ew6sqViodqQRg=,tag:P9S/o8Whue2f6M6qmF/kJQ==,type:str]
    erlangCookie: ENC[AES256_GCM,data:aNyfS0PVGe1zHTD145BS4oYTv3IxaSLSJiF5p1KK5v0=,iv:o6f7138zqtKOcp3L1xgSSxHCT1MmYCNJbHCUQs9I1rI=,tag:F9dG6LX3b/2gjZbWK0Q5Iw==,type:str]
basicAuth:
    tempo:
        password: ENC[AES256_GCM,data:9Xd0T3+KfmgfO8uj2PqID34DmIxfrRuw,iv:+X4FCp1U9aYL79ub23geozE6b6K7lVyN87T1y7wmqdk=,tag:Meod3nFuCHIJu7g0hV2BcQ==,type:str]
        htpasswd: ENC[AES256_GCM,data:hyhepqHSOOet4y8duSm281MZz3v2dcnekZDo6GrKY2z90UAsv+/J54jK2FRunA==,iv:Qy1qa+5m2RyHIgSS9zJCoLBoGLoAF+oh0nQOdQvUqBg=,tag:9PWqGPtF6TmT8oX8ee+t9w==,type:str]
    prometheus:
        password: ENC[AES256_GCM,data:UCAwoOqIMDYlSlD3434EIkr37DpXUuGd,iv:Uf3mp5MQoUu7A/iqh3ydQiE/GMAEZFIrDu7WWgdPqkg=,tag:W+4qWTJnJuKuqI6K3D2dlw==,type:str]
        htpasswd: ENC[AES256_GCM,data:txixDwQyyoc0j7u+uLJ5+uamH4v9ijyJSVqWqMfsY3xUlqaCsFM/snL2jPaFvg==,iv:Q2aejPIN2wdexvIGwqEv826Vy0y58jpuLX7VwG9PpfY=,tag:t+rlpwADg20ctCFT0wvIyw==,type:str]
    rawDataBridge:
        password: ENC[AES256_GCM,data:ATJNLgZq7s3bFlUjQSTCIlMHgU4BdTrA,iv:TYDcG8RbYq/F7QdXl3G8CKayHY5tNT0StrXQXwb0X4k=,tag:GrCteJMgF6ME3CeW7MtcdQ==,type:str]
        htpasswd: ENC[AES256_GCM,data:Sh4FwU24CRcHwJDRsUUa6uCjWBUOoFcxJRrLhX8vRdMBOUYVd0HqYucH7v4Xqw==,iv:TJISZYG6MiBL+A5l3KfiYZ8VoeGh9bW/BXFtOJk2ftA=,tag:e9qrNH6Y9hD/GL1Ya/mVCg==,type:str]
registry:
    readToken: ENC[AES256_GCM,data:DxFlPL1EJW9/vQg0TvYkxCJAYEQyUyk0p340QezZaZuRd1LxCBoH8g==,iv:JRRkqeEOizQEkbEiuMJekz6455+613ExAxDWkDUUL48=,tag:t3ptiKPYPziVFTaSyOQkQA==,type:str]
    readWriteToken: ENC[AES256_GCM,data:E+kypm3shuTZgm5Fgyl+cP72rTB47jy+F1b6ZGwBPI7zRKFE2a3xlA==,iv:ncDVMMfUdibc7DWswfr7Rhxve73BV5Zu6GQT9cnu+vw=,tag:X38JG71a3gzKX111CcZqBw==,type:str]
postgres:
    host: ENC[AES256_GCM,data:a1Wo8QbPw7yAV4Kf8MY=,iv:q9SNoZcI8hZLjxAFZCYZo7i5su5uXkyoAmV8bsY1H6s=,tag:C0MyQQCJioQ8SY7QO99WJA==,type:str]
    port: ENC[AES256_GCM,data:P0xIzJk=,iv:2IyumpNFl6RO7y/x/096TdYY16ApvAo8BfItMfSrnu0=,tag:ppQwtM43u1K83qEEGGBTAg==,type:str]
    readwritePassword: ENC[AES256_GCM,data:Lg0A+ywr2YwswqWozylK6U7wk7PWsX95RbGKQMSAJ+c=,iv:ZAcfaSpt8+i91AayQU07QrrIw2o0FRhhoinyvSG+wQU=,tag:kIxLfxUvxKIdxcvIRfx54Q==,type:str]
    readonlyPassword: ENC[AES256_GCM,data:iE5EvFXOCVe3//xH6qyrxZBFw7vjuXWO9w8u92W+ziY=,iv:minleBWa0gzdRXYLixf94EnaZW9kaiiwOhqELiQ3WrU=,tag:fevbiMtF6DdFYJt8qxC8Gw==,type:str]
rawS3:
    bucketName: ENC[AES256_GCM,data:xaryz86PhwmheXK+uj9KBic+pPo=,iv:DHLedDLG0hxGGHi7ZUl6/MLw8YDe6/BjGcX5TZ/NywY=,tag:gL3XbPw+LYVPwVncKy5tTQ==,type:str]
    accessKeyId: ENC[AES256_GCM,data:Bi0nBkt0Y21N9eiKaRBktROhkUA=,iv:kOgcoVapbdrhhRILfUQbLpe+H8mu/ypOVOCOxAjO5Pk=,tag:MWYkbMA/7mclvzymxF6hjA==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:u2Ef4lfM1sR4HQVfbkBDT6UM3q8ksuEJxgMTpYLUTp7bNhqt,iv:R8IAZkHeZcUQu8Bz0VV4/0liDyc48kNTHlzeFKT0B/I=,tag:uRkhVJeRzcExrnSRVgzmLQ==,type:str]
velero:
    accessKey: ENC[AES256_GCM,data:rohXIHlQ72KKkhozGN/lWi17yRk=,iv:ax3uLERb44Ftt3phy6mbTngxgRWHy49LCsdayUBAjqc=,tag:JiR9g0CsRiI4AHjwtPn1IQ==,type:str]
    secretKey: ENC[AES256_GCM,data:xwuUJiDYd8LZNmYk+zqp+taleozxutp8YDF6RGWd1SmHwL/U,iv:Cx5CenCWfZT4K+awkcvt/KM2g+GV6LXBIQRukjLE+dw=,tag:O7AnfBa8Zh0kW0ffPn8h/g==,type:str]
oauthCollector:
    clientSecret: ENC[AES256_GCM,data:jsqMONtucPQSWPjfDkNCTj9pERH5XDUvsw5SsAxFIBI7EHh8,iv:NIaSHldUGpASZWXchfVrf411gRZnQ89mekg/369C51w=,tag:cCMQphqCgbRwEstu5EGOEA==,type:str]
tourism:
    pgconnection: ENC[AES256_GCM,data:CNnt7RAh5M4LzxnrpHN8qRLsJiC+ydkPE4/q3nZ74nXt/LU/yu3WQDqq2MNheIoy0KUC8a5nFpg1ESeyXlCAIfysl6jDlHyXOz8sZ491XqfE+YcpAd3W77rQqbBb859QE5rrx1NYfhg=,iv:5CoTXbV2tzi0HgyTEl0bRPYh8jUe01mxjRzz14Ccdb8=,tag:uRjWAW/TNAZL/xmQ7bFiCw==,type:str]
scalewayDns:
    accessKey: ENC[AES256_GCM,data:yIeejBPacB3PkW93B//V13/3yF0=,iv:9o0PFVVEZWcrMYZeTpQCd/o7G68NyxUVnADGh8Jgdb4=,tag:FUaX5RY0l7HF923jZyGPAA==,type:str]
    secretKey: ENC[AES256_GCM,data:/EbDgsew+hVmDxeDuy383HxA2LZg4uOeRQudJYSlASoSuYiN,iv:1CCAR9Qse00yllmFBFePa76C/uf97k0ELCuzURzvSfY=,tag:LUwS9+ZbiqJvd5bybsBLSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMTNFYmdJN1dBSlNHODVQ
            ZnVZY3BJU2R0RkgwNXhXTU1oejBPQlp2SkFnCjlEMmZWOVg3QW9pb3dJS1hObW1u
            bXpMWTJwdEoyYmNQQWc1bTZtU2FKYlEKLS0tIExqNkZhVVNndWZFVHdZR2w1UjlP
            Q3JIR3FQcEVWTFdTNDBqUVhKb3NMc00KueqLc4vy5jxkq3ccouht8tfdDTm/w58e
            hCL5D+FZHjoCi3owyA58HT3NNFRgQLzKk3Uaxbg7nLOsBY4kTaxNow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8wawudpvktz6ceemnjh7ds2ecp69xhq5awmlenetmwhq4kz0saqvhy67r
    lastmodified: "2026-10-01T09:37:01Z"
    mac: ENC[AES256_GCM,data:46sHjOhiQhyOSKx51VGfWaoEKE76bKgVtqynVqT4s7n4GxIxW7yGfaJcMxX8VikPw32eXiX4HrwIUDpIidAbFjmkriPWfncrLnsM2QXzZukZJy7+SFDN1Xk7fxf4JTPrzB1BeTyS9Gb9HOUBLceEKhGGOxDmVqwHFNhfWLyBZsI=,iv:5J4anb2phrpqDD2Ez6WEoso6yZ/i44LKigq8qQEv8Gc=,tag:J7ptE5uWSJweXTpo3FoSHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
